---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-flag-admin # TODO 变量
  namespace: app
  labels:
    appid: feature-flag-admin # TODO 变量
spec:
  replicas: 2 # TODO 变量
  selector:
    matchLabels:
      appid: feature-flag-admin # TODO 变量
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: app
      labels:
        appid: feature-flag-admin # TODO 变量
    spec:
      imagePullSecrets:
        - name: my-cluster-registry-secret
      containers:
        - image: registry.my-cluster.co:5000/feature-flag-admin # TODO 变量
          name: feature-flag-admin # TODO 变量
          imagePullPolicy: IfNotPresent
          env:
            - name: appid
              value: feature-flag-admin # TODO 变量
          ports:
            - containerPort: 8000
            - containerPort: 9000
          # volumeMounts:
          #   - name: XXXX
          #     mountPath: XXXX
---
apiVersion: v1
kind: Service
metadata:
  name: feature-flag-admin-svc # TODO 变量
  namespace: app
  labels:
    appid: feature-flag-admin # TODO 变量
spec:
  type: ClusterIP
  selector:
    appid: feature-flag-admin # TODO 变量
  ports:
    - protocol: TCP
      name: http
      port: 8000
      targetPort: 8000
    - protocol: TCP
      name: grpc
      port: 9000
      targetPort: 9000
