apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.ProjectName}}-{{.ServiceName}}
  namespace: app
  labels:
    appid: {{.ProjectName}}-{{.ServiceName}}
spec:
  replicas: {{.PodCount}}
  selector:
    matchLabels:
      appid: {{.ProjectName}}-{{.ServiceName}}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      namespace: app
      labels:
        appid: {{.ProjectName}}-{{.ServiceName}}
    spec:
      imagePullSecrets:
        - name: my-cluster-registry-secret
      containers:
        - image: registry.my-cluster.co:5000/{{.ProjectName}}-{{.ServiceName}}:{{.Version}}
          name: {{.ProjectName}}-{{.ServiceName}}
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
          env:
            - name: appid
              value: {{.ProjectName}}-{{.ServiceName}}
          ports:
            - containerPort: 8000
            - containerPort: 9000
          # volumeMounts:
          #   - name: XXXX
          #     mountPath: XXXX