apiVersion: v1
kind: Service
metadata:
  name: {{.ProjectName}}-{{.ServiceName}}-svc
  namespace: app
  labels:
    appid: {{.ProjectName}}-{{.ServiceName}}
spec:
  type: ClusterIP
  selector:
    appid: {{.ProjectName}}-{{.ServiceName}}
  ports:
    - protocol: TCP
      name: http
      port: 8000
      targetPort: 8000
    - protocol: TCP
      name: grpc
      port: 9000
      targetPort: 9000
